<Project>
  <PropertyGroup>
    <ProductVersion>2.0.15</ProductVersion>
    <Version>$(ProductVersion)</Version>
    <AssemblyVersion>$(ProductVersion).0</AssemblyVersion>
    <FileVersion>$(ProductVersion).0</FileVersion>
    <InformationalVersion Condition="'$(SourceRevisionId)' != ''">$(ProductVersion)+$(SourceRevisionId)</InformationalVersion>
    <InformationalVersion Condition="'$(SourceRevisionId)' == ''">$(ProductVersion)</InformationalVersion>
    <CompanyName>Estudio Socratico</CompanyName>
    <Authors>Estudio Socratico</Authors>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RepositoryType>git</RepositoryType>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <AcceptEula>wix7</AcceptEula>
  </PropertyGroup>
</Project>
